// Generated by CoffeeScript 1.6.3
(function() {
  var Hapi, Lab, after, before, describe, expect, it;

  Lab = require('lab');

  Hapi = require('hapi');

  expect = Lab.expect;

  before = Lab.before;

  after = Lab.after;

  describe = Lab.experiment;

  it = Lab.test;

  describe('/users/me', function() {
    return it('GET returns an error when requested without auth', function(done) {
      return done();
    });
  });

}).call(this);
